/*
 * ADOBE CONFIDENTIAL
 * ___________________
 * Copyright 2025 Adobe
 * All Rights Reserved.
 * NOTICE: All information contained herein is, and remains
 * the property of Adobe and its suppliers, if any. The intellectual
 * and technical concepts contained herein are proprietary to Adobe
 * and its suppliers and are protected by all applicable intellectual
 * property laws, including trade secret and copyright laws.
 *  Dissemination of this information or reproduction of this material
 * is strictly forbidden unless prior written permission is obtained
 * from Adobe.
 */

// This file is auto-generated by scripts/generate-eds-widgets-index.js.
// Do not edit this file directly.

import { widgetMeta as bookBmwTestDriveMeta } from './bookBmwTestDrive/widget';
import { widgetMeta as getAdobeShirtsMeta } from './getAdobeShirts/widget';
import { widgetMeta as getBmwModelsMeta } from './getBmwModels/widget';
import { widgetMeta as getCoffeeDetailsMeta } from './getCoffeeDetails/widget';
import { widgetMeta as getCoffeeListMeta } from './getCoffeeList/widget';
import { widgetMeta as helloWorldEDSMeta } from './helloWorldEDS/widget';
import actions from './index';

export interface MCPResource {
  uri: string;
  name: string;
  description: string;
  mimeType: string;
  content: string;
  htmlFile?: string;
  _meta?: Record<string, any>;
}

// Widget resources with embedded HTML content
const bookBmwTestDriveResource: MCPResource = {
  ...bookBmwTestDriveMeta,
  content: `<script src="https://main--eds-001--george-cgg.aem.page/scripts/aem-embed.js" type="module"></script>
<div>
    <aem-embed url="https://main--eds-001--george-cgg.aem.page/eds-widgets/bmw-test-drive"></aem-embed>
</div>
`
};

const getAdobeShirtsResource: MCPResource = {
  ...getAdobeShirtsMeta,
  content: `<script src="https://main--eds-001--george-cgg.aem.page/scripts/aem-embed.js" type="module"></script>
<div>
    <aem-embed url="https://main--eds-001--george-cgg.aem.page/eds-widgets/adobe-shirts"></aem-embed>
</div>
`
};

const getBmwModelsResource: MCPResource = {
  ...getBmwModelsMeta,
  content: `<script src="https://main--eds-001--george-cgg.aem.page/scripts/aem-embed.js" type="module"></script>
<div>
    <aem-embed url="https://main--eds-001--george-cgg.aem.page/eds-widgets/bmw-models"></aem-embed>
</div>
`
};

const getCoffeeDetailsResource: MCPResource = {
  ...getCoffeeDetailsMeta,
  content: `<script src="https://main--eds-001--george-cgg.aem.page/scripts/aem-embed.js" type="module"></script>
<div>
    <aem-embed url="https://main--eds-001--george-cgg.aem.page/eds-widgets/frescopa-coffee-details"></aem-embed>
</div>
`
};

const getCoffeeListResource: MCPResource = {
  ...getCoffeeListMeta,
  content: `<script src="https://main--eds-001--george-cgg.aem.page/scripts/aem-embed.js" type="module"></script>
<div>
    <aem-embed url="https://main--eds-001--george-cgg.aem.page/eds-widgets/frescopa-coffee-list"></aem-embed>
</div>
`
};

const helloWorldEDSResource: MCPResource = {
  ...helloWorldEDSMeta,
  content: `<script src="https://main--eds-001--george-cgg.aem.live/scripts/aem-embed.js" type="module"></script>
<div>
    <aem-embed url="https://main--eds-001--george-cgg.aem.live/eds-widgets/hello-world"></aem-embed>
</div>
`
};

// Dynamically collect resources for actions that have widgets
const staticResources: MCPResource[] = [
  // Add any static resources here if needed
];

// Add resources for actions with hasAemWidget: true
const widgetActions = actions.filter(action => action.hasAemWidget);
const widgetResources: MCPResource[] = [
  bookBmwTestDriveResource,
  getAdobeShirtsResource,
  getBmwModelsResource,
  getCoffeeDetailsResource,
  getCoffeeListResource,
  helloWorldEDSResource,
];

// Combine all resources
const resources: MCPResource[] = [...staticResources, ...widgetResources];

// Log AEM Widget registration with nice formatting (consistent with actions logging)
if (resources.length > 0) {
  console.log(`\n[lcb-server] Successfully generated server/src/actions/index-widgets.ts with ${resources.length} AEM Widgets:`);
  resources.forEach(resource => {
    const resourceFile = resource.uri.split('/').pop();
    console.log(`- ${resourceFile} -> ${resource.name} (type: ${resource.mimeType})`);
  });
} else {
  console.log('[lcb-server] No AEM Widgets registered');
}

// Log widget actions that have AEM Widgets
if (widgetActions.length > 0) {
  console.log(`\n[lcb-server] Widget-enabled actions with AEM Widgets:`);
  widgetActions.forEach(action => {
    console.log(`- ${action.name}`);
  });
}

// Create lookup maps for efficient access
export const resourcesByUri = new Map<string, MCPResource>();

resources.forEach((resource) => {
  resourcesByUri.set(resource.uri, resource);
});

// Helper function to get resource by URI
export function getResourceByUri(uri: string) {
  const resource = resourcesByUri.get(uri);
  if (!resource) {
    return null;
  }
  
  return {
    contents: [
      {
        uri: resource.uri,
        mimeType: resource.mimeType,
        text: resource.content,
        _meta: resource._meta
      }
    ]
  };
}

export { resources };
export default resources;
