/*
 * ADOBE CONFIDENTIAL
 * ___________________
 * Copyright 2025 Adobe
 * All Rights Reserved.
 * NOTICE: All information contained herein is, and remains
 * the property of Adobe and its suppliers, if any. The intellectual
 * and technical concepts contained herein are proprietary to Adobe
 * and its suppliers and are protected by all applicable intellectual
 * property laws, including trade secret and copyright laws.
 *  Dissemination of this information or reproduction of this material
 * is strictly forbidden unless prior written permission is obtained
 * from Adobe.
 */


// This file is auto-generated by scripts/generate-actions-from-schemas.js
// Do not edit this file directly.

import { z } from 'zod';
import * as mod_bookBmwTestDrive from './bookBmwTestDrive';
import * as mod_getAdobeShirts from './getAdobeShirts';
import * as mod_getBmwModels from './getBmwModels';
import * as mod_getCoffeeDetails from './getCoffeeDetails';
import * as mod_getCoffeeList from './getCoffeeList';
import * as mod_helloWorldEDS from './helloWorldEDS';

const actions = [
  {
    name: "bookBmwTestDrive",
    version: "0.0.1",
    isPublished: true,
    hasAemWidget: true,
    definition: {
      title: "BookBmwTestDrive",
      description: "Book a test drive for a BMW vehicle at a local dealership.",
      inputSchema: z.object({ "vehicleModel": z.string().trim(), "location": z.string().trim() }),
      inputSchemaJson: {"type":"object","properties":{"vehicleModel":{"type":"string","description":"BMW vehicle model (e.g., X5 xDrive40i, 330i xDrive Sedan, i4 eDrive40, X3 30 xDrive)"},"location":{"type":"string","description":"Dealership location (e.g., Manhattan)"}},"required":["vehicleModel","location"]},
      annotations: {"destructiveHint":false,"openWorldHint":false,"readOnlyHint":false},
      _meta: {"openai/outputTemplate":"ui://eds-widget/bmw-test-drive-widget.html","openai/widgetAccessible":true,"openai/toolInvocation/invoking":"Loading test drive booking...","openai/toolInvocation/invoked":"Test drive booking ready","openai/resultCanProduceWidget":true}
    },
    handler: mod_bookBmwTestDrive.handler,
    fileName: 'bookBmwTestDrive/index.ts'
  },
  {
    name: "getBmwModels",
    version: "0.0.1",
    isPublished: true,
    hasAemWidget: true,
    definition: {
      title: "GetBmwModels",
      description: "Gets BMW vehicle models with current lease offers and promotions.",
      inputSchema: z.object({ "category": z.enum(["all", "SUV", "Sedan", "Electric"]).optional() }),
      inputSchemaJson: {"type":"object","properties":{"category":{"type":"string","enum":["all","SUV","Sedan","Electric"],"description":"Filter by vehicle category (default: all)"}},"required":[]},
      annotations: {"destructiveHint":false,"openWorldHint":false,"readOnlyHint":true},
      _meta: {"openai/outputTemplate":"ui://eds-widget/bmw-models-widget.html","openai/widgetAccessible":true,"openai/toolInvocation/invoking":"Loading BMW models...","openai/toolInvocation/invoked":"BMW models ready","openai/resultCanProduceWidget":true}
    },
    handler: mod_getBmwModels.handler,
    fileName: 'getBmwModels/index.ts'
  }
];

export default actions;
