/*
 * ADOBE CONFIDENTIAL
 * ___________________
 * Copyright 2025 Adobe
 * All Rights Reserved.
 * NOTICE: All information contained herein is, and remains
 * the property of Adobe and its suppliers, if any. The intellectual
 * and technical concepts contained herein are proprietary to Adobe
 * and its suppliers and are protected by all applicable intellectual
 * property laws, including trade secret and copyright laws.
 *  Dissemination of this information or reproduction of this material
 * is strictly forbidden unless prior written permission is obtained
 * from Adobe.
 */


// This file is auto-generated by scripts/generate-actions-from-schemas.js
// Do not edit this file directly.

import { z } from 'zod';
import * as mod_getCoffeeDetails from './getCoffeeDetails';
import * as mod_getCoffeeList from './getCoffeeList';
import * as mod_helloWorldEDS from './helloWorldEDS';

const actions = [
  {
    name: "getCoffeeDetails",
    version: "1.0.0",
    isPublished: true,
    hasAemWidget: true,
    definition: {
      title: "GetCoffeeDetails",
      description: "Get detailed information about a specific Frescopa coffee product by ID",
      inputSchema: z.object({ "coffeeId": z.string().trim() }),
      inputSchemaJson: {"type":"object","properties":{"coffeeId":{"type":"string","description":"The ID of the coffee product (e.g., hbdr212, pod311)"}},"required":["coffeeId"]},
      annotations: {"destructiveHint":false,"openWorldHint":false,"readOnlyHint":true},
      _meta: {"openai/outputTemplate":"ui://eds-widget/frescopa-coffee-details.html","openai/widgetAccessible":true,"openai/toolInvocation/invoking":"Loading coffee details...","openai/toolInvocation/invoked":"Coffee details ready","openai/resultCanProduceWidget":true}
    },
    handler: mod_getCoffeeDetails.handler,
    fileName: 'getCoffeeDetails/index.ts'
  },
  {
    name: "getCoffeeList",
    version: "0.0.1",
    isPublished: true,
    hasAemWidget: true,
    definition: {
      title: "GetCoffeeList",
      description: "Gets Frescopa coffee products including Bagged Coffee and Coffee Pods.",
      inputSchema: z.object({  }),
      inputSchemaJson: {"type":"object","properties":{},"required":[]},
      annotations: {"destructiveHint":false,"openWorldHint":false,"readOnlyHint":true},
      _meta: {"openai/outputTemplate":"ui://eds-widget/frescopa-coffee-list.html","openai/widgetAccessible":true,"openai/toolInvocation/invoking":"Loading coffee list...","openai/toolInvocation/invoked":"Coffee list ready","openai/resultCanProduceWidget":true}
    },
    handler: mod_getCoffeeList.handler,
    fileName: 'getCoffeeList/index.ts'
  },
  {
    name: "helloWorldEDS",
    version: "0.0.1",
    isPublished: true,
    hasAemWidget: true,
    definition: {
      title: "Hello World EDS",
      description: "Returns a heartbeat timestamp in a nice visual widget with rounded corners and centered styling. Displays current server time in an interactive card format.",
      inputSchema: z.object({  }),
      inputSchemaJson: {"type":"object","properties":{},"required":[]},
      annotations: {"destructiveHint":false,"openWorldHint":false,"readOnlyHint":true},
      _meta: {"openai/outputTemplate":"ui://eds-widget/hello-world-eds-widget.html","openai/toolInvocation/invoking":"Saying hello world from EDS","openai/toolInvocation/invoked":"Said hello world from EDS","openai/widgetAccessible":true,"openai/resultCanProduceWidget":true}
    },
    handler: mod_helloWorldEDS.handler,
    fileName: 'helloWorldEDS/index.ts'
  }
];

export default actions;
