/*
 * ADOBE CONFIDENTIAL
 * ___________________
 * Copyright 2025 Adobe
 * All Rights Reserved.
 * NOTICE: All information contained herein is, and remains
 * the property of Adobe and its suppliers, if any. The intellectual
 * and technical concepts contained herein are proprietary to Adobe
 * and its suppliers and are protected by all applicable intellectual
 * property laws, including trade secret and copyright laws.
 *  Dissemination of this information or reproduction of this material
 * is strictly forbidden unless prior written permission is obtained
 * from Adobe.
 */

// This file is auto-generated by scripts/generate-actions-index.js.
// Do not edit this file directly.

import bitdefenderGetProductDetails from './bitdefenderGetProductDetails';
import bitdefenderSearchProducts from './bitdefenderSearchProducts';

const actions = [
  {
    ...bitdefenderGetProductDetails,
    version: bitdefenderGetProductDetails.version,
    fileName: 'bitdefenderGetProductDetails/index.ts'
  },
  {
    ...bitdefenderSearchProducts,
    version: bitdefenderSearchProducts.version,
    fileName: 'bitdefenderSearchProducts/index.ts'
  }
];

export default actions;
