/*
 * ADOBE CONFIDENTIAL
 * ___________________
 * Copyright 2025 Adobe
 * All Rights Reserved.
 * NOTICE: All information contained herein is, and remains
 * the property of Adobe and its suppliers, if any. The intellectual
 * and technical concepts contained herein are proprietary to Adobe
 * and its suppliers and are protected by all applicable intellectual
 * property laws, including trade secret and copyright laws.
 *  Dissemination of this information or reproduction of this material
 * is strictly forbidden unless prior written permission is obtained
 * from Adobe.
 */

// This file is auto-generated by scripts/generate-actions-index.js.
// Do not edit this file directly.

import contentSearch from './contentSearch';
import heartbeat from './heartbeat';
import heartbeatWidget from './heartbeatWidget';
import helloWorldEDS from './helloWorldEDS';
import previewContentFragment from './previewContentFragment';
import searchContentFragments from './searchContentFragments';
import systemStatusWidget from './systemStatusWidget';

const actions = [
  {
    ...contentSearch,
    version: contentSearch.version,
    fileName: 'contentSearch/index.ts'
  },
  {
    ...heartbeat,
    version: heartbeat.version,
    fileName: 'heartbeat/index.ts'
  },
  {
    ...heartbeatWidget,
    version: heartbeatWidget.version,
    fileName: 'heartbeatWidget/index.ts'
  },
  {
    ...helloWorldEDS,
    version: helloWorldEDS.version,
    fileName: 'helloWorldEDS/index.ts'
  },
  {
    ...previewContentFragment,
    version: previewContentFragment.version,
    fileName: 'previewContentFragment/index.ts'
  },
  {
    ...searchContentFragments,
    version: searchContentFragments.version,
    fileName: 'searchContentFragments/index.ts'
  },
  {
    ...systemStatusWidget,
    version: systemStatusWidget.version,
    fileName: 'systemStatusWidget/index.ts'
  }
];

export default actions;
