name: Boilerplate - Build, Test and Deploy
permissions:
  contents: read
on:
  push:
    branches:
      - main
jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    environment: 'MAIN_ENV'
    env:
      AEM_COMPUTE_TOKEN: ${{ secrets.AEM_COMPUTE_TOKEN }}
      AEM_COMPUTE_SERVICE: ${{ vars.AEM_COMPUTE_SERVICE }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install required system dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential
      
      - name: Install dependencies
        run: |
          rm -rf node_modules package-lock.json
          npm install
      
      - name: Generate action and widget indexes
        run: make generate-all
      
      - name: Run tests
        run: make test
      
      - name: Build TypeScript
        run: npm run build
      
      - name: Install Fastly CLI
        run: npm install -g @fastly/cli
      
      - name: Build WASM with js-compute-runtime
        run: npm run build:fastly
      
      - name: Build Fastly Compute package
        run: fastly compute build
      
      - name: Verify build artifacts
        run: |
          test -f bin/main.wasm || (echo "WASM file not generated" && exit 1)
          test -f pkg/llm-conversion-bridge.tar.gz || (echo "Package not generated" && exit 1)
          echo "✓ Build artifacts verified successfully"
      
      - name: Deploy to Fastly Compute
        if: success()
        run: make deploy
